//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularMVCTest1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Info
    {
        public int OrderId { get; set; }
        public string CustomerName { get; set; }
        public string Address { get; set; }
        public string OrderInfo { get; set; }
        public string Employee { get; set; }
        public Nullable<System.DateTime> FormalizationDate { get; set; }
        public bool Formalizated { get; set; }
        public bool Delivered { get; set; }
    }
}
